### PR TITLE
Fix typo in readme

### PR DESCRIPTION
**Pull request by ckelner**

### CODE REVIEW

**Comment by alokmenghrajani** [comment]
Thanks for fixing this. It's sad, but we require a CLA for every commit, even a simple fix like this one.

Can you please sign https://spreadsheets.google.com/spreadsheet/viewform?formkey=dDViT2xzUHAwRkI3X3k5Z0lQM091OGc6MQ&ndplr=1

**Comment by ckelner** [comment]
@alokmenghrajani all done :dancer:

**Comment by sul3n3t** [comment]
Thanks!

**Comment by ckelner** [comment]
No problem! :)  Hopefully I'll have more meaningful things to contribute in the future!  Looks awesome!

**Pull request merged**
