### PR TITLE
Use maven wrapper for fully encapsulated build setup.

### PR DESCRIPTION
**Pull request by sureshg**
The following changes have included in this PR.

* Use maven wrapper (3.3.9) for fully encapsulated build setup. With this changes, if a user doesn't have the necessary version of Maven installed, it will be downloaded for the user first.

* Updated to the latest version of `maven-shade-plugin` plugin (`2.4.3`). This version fixes issue #301 and [JIRA MSHADE-183](https://issues.apache.org/jira/browse/MSHADE-183) (which is mentioned in [pom.xml](https://github.com/square/keywhiz/blob/master/pom.xml#L436))

### CODE REVIEW

**Comment by mcpherrinm** [comment]
This seems reasonable.

Is this https://github.com/takari/maven-wrapper?  I'll take a look at this project.

It seems a bit weird to me to be checking in a .jar, though.

Since I'm unfamiliar with this wrapper, as is the rest of the team, I'll want to take a little time to use it out.  Unfortunately it's already getting late on Friday, so it'll have to wait until next week.

**Comment by sureshg** [comment]
@mcpherrinm Yes, it's the takari maven wrapper.

> It seems a bit weird to me to be checking in a .jar, though.

This is very common and is the way to use gradle (Eg: https://github.com/spring-projects/spring-framework/tree/master/gradle/wrapper)

For more info, check this - https://docs.gradle.org/current/userguide/gradle_wrapper.html

**Comment by sureshg** [comment]
Any update on this?

**Comment by mcpherrinm** [comment]
I'm concerned that my team wouldn't use this tool, because it's not part of our usual workflow.

In my experience, anything like this we accept but don't use ends up broken, and does more harm than good.

**Pull request closed without merging**
