### PR TITLE
Cache ~/.m2

### PR DESCRIPTION
**Pull request by alokmenghrajani**
- [ ] @csstaub 
- [ ] @mcpherrinm

### CODE REVIEW

**Comment by csstaub** [comment]
Nice

**Comment by Taher-Ghaleb** [comment]
Hello,

Sorry, I know it's been a long time ago, but I am curious why caching hasn't been enabled before this (i.e., since December 17, 2014, when it became available to open source projects).

Thank you.

**Comment by mcpherrinm** [comment]
Why we didn’t cache between 2014 and 2016?  I think we didn’t have enough activity on this project to really care about CI build times.

**Comment by Taher-Ghaleb** [comment]
I got your point. Thank you, @mcpherrinm, for your response.

**Pull request merged**
