### PR TITLE
Update dropwizard version and configuration

### PR DESCRIPTION
**Pull request by sul3n3t**
Updates dropwizard from 0.8.0 -> 0.8.1
Removes RC4 cipher suites
Updates DB config for constant size pools and default readonly on readonly config

### CODE REVIEW

**Comment by alokmenghrajani** [comment]
:+1:

**Comment by riyazdf** [comment]
LGTM

**Comment by alokmenghrajani** [comment]
Is Dropwizard 0.8.1 stable? http://www.dropwizard.io/about/release-notes.html doesn't list it.

**Comment by sul3n3t** [comment]
Looks like they just haven't updated the website yet. It was released yesterday and I caught the [announcement email](https://groups.google.com/d/topic/dropwizard-user/SWppAbSJO70/discussion). Pretty minor fixes in the release.

**Pull request merged**
