### PR TITLE
Add ability to search/replace intermediate certificates.

### PR DESCRIPTION
**Pull request by alokmenghrajani**
- [ ] @csstaub 
- [ ] @mcpherrinm

### CODE REVIEW

**Comment by mcpherrinm** [comment]
Why is this endpoint unauthenticated?

**Comment by alokmenghrajani** [comment]
Easier to test (I would need to modify `keywhiz.client.KeywhizClient` otherwise) and easier to use (we'll have to write some kind of loop to hit this endpoint for every secret). The endpoint doesn't take the cert to search or replace (that's configured in the yaml file) so it seems fine.

**Comment by mcpherrinm** [comment]
We could make it an automation endpoint instead of admin, and you just hit it with curl & a client cert

**Comment by mcpherrinm** [comment]
This looks okay from a high level.  We should talk tomorrow about how we want to move forward with this (should we merge, or use it from a branch?)

**Comment by alokmenghrajani** [comment]
Plan is to keep this in a branch.

**Pull request closed without merging**
