### PR TITLE
Add HMAC column to secrets_content table

### PR DESCRIPTION
**Pull request by jbpeirce**

### CODE REVIEW

**Comment by mcpherrinm** [comment]
I think we should probably use an appropriately sized BINARY, not `text`.

**Comment by alokmenghrajani** [comment]
Storing hex-encoded strings makes other things slightly easier.

**Comment by csstaub** [comment]
Why TEXT, why not CHAR (or VARCHAR) with fixed length? Consider http://mysqlserverteam.com/externally-stored-fields-in-innodb/

**Comment by alokmenghrajani** [comment]
VARCHAR(64) would work too.

**Pull request merged**
